# Generated by Django 3.1.7 on 2021-03-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0002_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('img1', models.ImageField(blank=True, upload_to='description/')),
                ('img2', models.ImageField(blank=True, upload_to='description/')),
                ('img3', models.ImageField(blank=True, upload_to='description/')),
                ('color1', models.CharField(blank=True, max_length=30)),
                ('color2', models.CharField(blank=True, max_length=30)),
                ('color3', models.CharField(blank=True, max_length=30)),
                ('size1', models.CharField(blank=True, max_length=30)),
                ('size2', models.CharField(blank=True, max_length=30)),
                ('size3', models.CharField(blank=True, max_length=30)),
                ('rated', models.IntegerField(default=5)),
                ('ratees', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='nora.product')),
            ],
        ),
    ]
