# Generated by Django 3.1.7 on 2021-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0004_auto_20210328_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.ImageField(upload_to='staronly/')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
