# Generated by Django 3.1.7 on 2021-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nora', '0005_auto_20210328_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order',
            field=models.IntegerField(default=2),
        ),
    ]
